### ISSUE TITLE
[QNA-Issue] Ambiguity in meaning of "Mahabharat" (epic or battle) in datasets_used/QA_dataset.csv/Q22

### ISSUE THREAD

**Issue by arjunvenkatraman** [Palakgarg155/Multilingual-RAG-Evaluations#1]
File: datasets_used/QA_dataset.csv 
Question #: 22
Issue: The questions asks who was the king at the beginning of the Mahabharata - this may be correctly answered as Shantanu or Dhritarashtra depending on whether the meaning of the word Mahabharat is taken as the battle or the epic

**Comment by aditisinghh17** [comment]
Our knowledge base uses Mahabharata in the context of the epic, so the correct answer would be Shantanu.
